# CI Config for Test_Project / gitlab
stages:
  - build
  - test

# Global runner/docker image definition
image: openjdk:8

# Main build 
build: 
  stage: build
  tags:
    - docker
  script:
    - ./gradlew build


# Tests 
tests:
  stage: test
  tags:
    - docker
  dependencies:
    - build
  script:
    - ./gradlew test
  artifacts:
    when: always
    untracked: true
    paths:
      - build
    expire_in: 10d


