# CI Config for Test_Project / gitlab
stages:
  - build
  - test
  - deploy

# Global runner/docker image definition
image: openjdk:8

# Main build 
build: 
  stage: build
  tags:
    - docker
  script:
    - ./gradlew build


# Tests 
tests:
  stage: test
  tags:
    - docker
  dependencies:
    - build
  script:
    - ./gradlew test
  artifacts:
    when: always
    untracked: true
    paths:
      - build
    expire_in: 10d


# Run the main and show the tests results
pages:
  stage: deploy
  tags:
    - docker
  script:
    - ./gradlew run
    - ./gradlew javadoc
    - ./gradlew jar
    - mkdir -p public/ && cp -r index.html public/
    - mkdir -p public/Tests_Results && cp -r build/reports/tests/test/* public/Tests_Results/
    - mkdir -p public/Jacoco && cp -r build/jacocoHtml/* public/Jacoco/
    - mkdir -p public/Javadoc && cp -r build/docs/javadoc/* public/Javadoc/
    - cp -r build/libs/ImmutableComplex-1.0.0.jar public/
  artifacts:
    paths:
      - public

