language: java

jdk:
  - oraclejdk8
  - openjdk8

script:
  - jdk_switcher use oraclejdk8
  - ./gradlew assemble
  - ./gradlew check
  - ./gradlew test
  - jdk_switcher use openjdk8
  - ./gradlew assemble
  - ./gradlew check
  - ./gradlew test
  - ./gradlew run
  - ./gradlew javadoc
  - ./gradlew jar
  - mkdir -p public/ && cp -r index_github.html public/index.html
  - mkdir -p public/Tests_Results && cp -r build/reports/tests/test/* public/Tests_Results/
  - mkdir -p public/Jacoco && cp -r build/jacocoHtml/* public/Jacoco/
  - mkdir -p public/Javadoc && cp -r build/docs/javadoc/* public/Javadoc/
  - cp -r build/libs/ImmutableComplex-1.0.0.jar public/

branches:
  only:
  - master

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $PAGE_TOKEN
  keep-history: true
  local-dir: public
  on:
    branch: master