language: java
jdk:
- oraclejdk8
- openjdk8
script:
- jdk_switcher use oraclejdk8
- "./gradlew assemble"
- "./gradlew check"
- "./gradlew build"
- "./gradlew test"
- jdk_switcher use openjdk8
- "./gradlew assemble"
- "./gradlew check"
- "./gradlew build"
- "./gradlew test"
- "./gradlew run"
- "./gradlew javadoc"
- "./gradlew jar"
- mkdir -p public/ && cp -r index.html public/
- mkdir -p public/Tests_Results && cp -r build/reports/tests/test/* public/Tests_Results/
- mkdir -p public/Jacoco && cp -r build/jacocoHtml/* public/Jacoco/
- mkdir -p public/Javadoc && cp -r build/docs/javadoc/* public/Javadoc/
- cp -r `ls -t build/libs/ImmutableComplex*.jar | head -1` public/
branches:
  only:
  - master
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$PAGE_TOKEN"
  keep-history: true
  local-dir: public
  on:
    branch: master
env:
  global:
  - 'GandiUSER=69442'
    secure: CFDlQ5tOsqsPJvXcNp+KyAqHmnKpQwQpVoRuud6CrsL3R670AjmBgmhiDHMUvHNSa+m2CbXkY2MIMnwVHCTrnX9Qlx/ZUPXRldZ6W2aTrCqYhze/1k3TUbKBA2udoB1kHQSsnGJohd2BC3Hj5fkknBUputzVQEwCzCIiaNTRV6F+bUyL3KjUS5seUVbZZ+WLk/TaOPxdrzvlBH+dr502Q6f8IhGExvITsOC9NsIxfsf2QjQuPzQPqx0aTavRXHnaKiaUb5wNmAvCbNvf4DuZFxWGa8VVXCgCeNgQ5q/3dS+Mgn4kWiYcJHmznrweMDl0SK6ujbEwqmxMb1+W/QAlaDJKxtveZXePcu8QOHGyCgQK79eFM0oVQy6opNpDwq6WVkc0z7Ix4rXCw4GCNzQA+O7rpcd9UxUc2V/7vw+cluMRofiwBGD+heuaizL50ONZPUcweZVDy72bzm1958CMPWLoNf6e9dcXOy/sU7Wv+kKJy+/00p/iRYpE+kkjnG09pbUw6R7lbpX1txPSQr9Rva1L0gPH041hT/iyABRUqDB4UWjpinJ2RoXgfRg398wymFqEp3mOirXYlJR3RhtF1RxUshpdfbu2YcaCS0v8sCi1VrbERx5jatOhxkg5WHWPrLJMw/CTuzu3NN+nB36a14TC1TjfOBgPYIdZgIF5Ge8=
  after_success:
  - find public/ -type f -exec curl -u ${GandiUSER}:${GandiPWD} --ftp-create-dirs -T {} sftp://sftp.sd6.gpaas.net/htdocs/{} \;
    
